#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd platforms && npx lint-staged

# if the branch is main, then fail.
branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"
if [ "${branch##refs/heads/}" = "main" ]; then
    echo "[Error] Can't commit on main branch."
    exit 1
fi